src/Routing/ResourceRegistrar.php

Fix for methods in relationship routes. Add support of options "only" and "except" in resource routes

Fix for methods in routes.

---

src/Http/Controllers/EloquentController.php

Adds callbacks for creating/created/updating/updated models on a controller.
Callbacks can be defined in controllers that inherit the `EloquentController`.
```php
class UsersController extends EloquentController
{
protected function creating(Model $model)
{
// Before the model is created.
}
protected function created(Model $model)
{
// After the model has been created.
}
protected function updating(Model $model)
{
// Before the model is updated.
}
protected function updated()
{
// After the model has been created.
}
}
```
---
See #11 for a bit more discussion.`

Before & After commit hooks

---

src/Console/Commands/AbstractGeneratorCommand.php

PHP 5.5 doesn't support scalar values in class property declarations. This can be fixed by moving it to the constructor.

[Bugfix] Fix unsupported scalar expression

---

src/Hydrator/EloquentHydrator.php
src/Schema/EloquentSchema.php

This implementation uses fillable attributes from eloquent models to avoid repetition of these attributes declaration in the schema and hydrator classes (by default, if attributes are declared in schema/hydrator class, these are used).

Get default attributes for schemas and hydrators from model fillable attribute

---

composer.json
tests/Integration/Routing/ResourceRegistrarTest.php
tests/Integration/TestCase.php

The Testbench project by Orchestral makes testing features that are tightly integrated with the Laravel framework a breeze. This allows for a hazzle-free testing environment, that might motivate writing more integration tests.

Use Orchestra Testbench for integration tests

---

docs/installation.md

The composer command to install the json-api-testing package had a typo

Fix typo in json-api-testing package name

---

stubs/api.php

I heard a lot of lovely things about this package! Thanks for all of the hard work.
With this pull request I added `JSON_PRESERVE_ZERO_FRACTION` to the default api config stub file.
In many situtations its preferred by clients (consumers of an API) to distinguish between actual floats or integers.

[Feature] Preserve Floats

---

docs/basics/schemas.md

Updated to match the order of the following three subsections

Fix order of relationship types in a schema

---

src/Http/Middleware/BootJsonApi.php

Concatenating `$request->getSchemeAndHttpHost()` with  `$request->getBaseUrl()` generates the correct URLs for subdirectory installs. I have tested this works with a Laravel 5.4 installation in both the root directory and a subdirectory.

Resolve API url generation issues for subdirectory installs.

---

src/Utils/Helpers.php

Laravel’s built-in HTTP Tests API sends a body for GET requests of `[]`.
This causes a JSON parsing failure as it’s not recognized as an object. It _should_ be recognized as an empty body, but it’s not. Adjusting this helper method fixes the issue while not causing any regressions in the test suite.

Improve compatibility with Laravel’s HTTP test API

---

src/Routing/RegistersResources.php
src/Routing/ResourceGroup.php
tests/lib/Integration/Issue224/IssueTest.php
tests/lib/Integration/Issue224/Schema.php
tests/lib/Integration/RoutingTest.php
tests/lib/Unit/Resolver/NamespaceResolverTest.php

Use the resource type and relationship name as provided - so that it can be camel case or snake case.
See #224

Do not dasherize resource type and relationship in route url

---

docs/fetching/filtering.md

While reading the library docs on readthedocs I saw the layout for fetching/filtering is a bit broken and syntax highlighting does not work.
This PR should fix it.

Fixing syntax highlighting and layout in docs

---

docs/basics/adapters.md
docs/upgrade.md
src/Adapter/AbstractResourceAdapter.php
src/Contracts/Adapter/ResourceAdapterInterface.php
src/Contracts/Store/StoreInterface.php
src/Eloquent/AbstractAdapter.php
src/Http/Controllers/JsonApiController.php
src/Http/Requests/FetchProcess.php
src/Http/Requests/JsonApiRequest.php
src/Store/Store.php
tests/lib/Integration/Eloquent/ResourceTest.php
tests/lib/Integration/FilterTest.php
tests/lib/Unit/Store/StoreTest.php

Previously the adapter read method took the resource ID has its first argument. This was inconsistent with all the other adapter methods that were to do with a specific record, as they all take the record being read as the first argument.
Because the record is already loaded via binding substitution, it also meant the record was being retrieved twice.
This PR fixes this by changing the method signature to receive the loaded record. It still needs to be passed to the adapter because there is other logic to implement - e.g. in the Eloquent adapter it is used for eager-loading based on the include paths, plus checking whether the record matches any supplied filter parameters.
Closes #256

[Refactor] Make adapter read method consistent

---

CHANGELOG.md
docs/features/media-types.md
src/Codec/Decoding.php
tests/dummy/app/JsonApi/Avatars/ContentNegotiator.php
tests/dummy/tests/Feature/Avatars/CreateTest.php

This commit adds temporary support for wildcard parameters for decoding media types. This is needed so that you can accept `multipart/form-data` which will have an unpredictable `boundary` parameter.
This is a temporary solution as `neomerx/json-api:^3.0` adds support for wildcard parameters when matching media types.
See #265

[Feature] Allow decoder wildcard media parameters

---

CHANGELOG.md
src/Adapter/AbstractResourceAdapter.php
src/Eloquent/AbstractAdapter.php
src/Eloquent/Concerns/IncludesModels.php

Allow developers to use the exact JSON API field name as the relationship method name on their
adapters, plus for default conversion of names in include paths. Although we recommend following
the PSR1 standard of using camel case for method names, this does allow a developer to use snake
case field names with snake case method names.
Closes #315

[Feature] Allow snake case relation names

---

CHANGELOG.md
docs/fetching/pagination.md
src/Eloquent/AbstractAdapter.php
src/Pagination/CursorStrategy.php
src/Pagination/StandardStrategy.php
tests/dummy/app/JsonApi/Posts/Validators.php
tests/dummy/app/JsonApi/Videos/Adapter.php
tests/dummy/app/JsonApi/Videos/Validators.php
tests/lib/Integration/Pagination/StandardPagingTest.php

Ensures records appear in the same order when using the standard strategy, by adding a deterministic sort order (i.e. sorting by the resource `id`).
Closes #313

[Bugfix] Add deterministic sort order to standard paging strategy

---

src/Eloquent/Concerns/SoftDeletesModels.php

If the softDeleteField is a nested attribute (ie status.deleted-at for example), we use Laravel Array Helpers to manage its value.

[Feature] Allow dot notation for soft delete field name

---

src/Validation/AbstractValidators.php

The methods used in return statement were inverted between delete and create requests.

[Bugfix] Fix wrong returned methods in validators

---

CHANGELOG.md
docs/basics/adapters.md
src/Eloquent/AbstractAdapter.php
tests/lib/Integration/Eloquent/ScopesTest.php

Allows global scopes to be applied to an Eloquent adapter, either via constructor dependency injection or a closure.
Closes #337

[Feature] Add Eloquent adapter scopes

---

src/Testing/TestResponse.php

`Assert::assertInternalType` was deprecated in PHPUnit 8. Recommended migration path is to use the assertions per type added in PHPUnit 7.5. This is `Assert:assertIsString` for our use case.
I wasn't quite sure which PHPUnit versions are supported. `composer.json` of this package lists `^6.0|^7.0`. Therefore I added a fallback for PHPUnit < 7.5.

fix: assertInternalType is deprecated

---

src/Http/Requests/ValidatedRequest.php

This adds support for retrieving a specific query param with a default value:
```php
$validatedRequest->query('name', 'Helen');
```
More information about that feature available in Laravel docs:
https://laravel.com/docs/5.8/requests#retrieving-input
It is available for all supported Laravel versions (5.5 and above).

query() method of ValidatedRequest should have same interface as Illuminate\Http\Request

---

src/Api/Api.php

```php
if (!$this->container) {
$this->container = $this->factory->createExtendedContainer($this->resolver);
}
return $this->container;
```
Factory::createExtendedContainer() always returns Container instance:
```php
/**
* @inheritdoc
*/
public function createExtendedContainer(ResolverInterface $resolver)
{
return new Container($this->container, $resolver);
}
```
This generates phpstan errors:
```php
-------------------------------------------------------------------------
Line   Base/Schema.php
-------------------------------------------------------------------------
48     Cannot call method getAdapterByResourceType() on
CloudCreativity\LaravelJsonApi\Contracts\ContainerInterface|null.
-------------------------------------------------------------------------
```
On this code:
```php
/** …
```

Api::getContainer() return type fixed

---

docs/index.md
docs/installation.md

Explicitly naming Laravel 5 was helpful for some time to distinguish from Laravel 4 packages. But as Laravel 6 and 7 were released this is confusing.
E.g. on StackOverflow someone assumed that this library is outdated as it's only for Laravel 5 and not for newer versions: https://stackoverflow.com/questions/60711249/how-to-use-jsonapi-spec-include-url-param-in-laravel-7-x-project?noredirect=1#comment107430380_60711249

explicitly naming Laravel 5 is confusing

---

src/Api/Url.php
tests/lib/Integration/Routing/RouteParameterTest.php

I noticed when I set my `url.namespace` to `api/v1/{tenant}`, if the `tenant` param was bound to a model the generated URLs would contain the JSON serialization, like so;
```json
"links": {
"self": "http:\/\/api.example.test\/api\/v1\/{\"id\":1,\"name\":\"Tenant Name\",\"created_at\":\"2020-04-20T13:57:55.000000Z\",\"updated_at\":\"2020-04-20T13:57:55.000000Z\",\"slug\":\"test-slug\"}\/products\/1"
}
```
With this fix, bound models correctly use the route key;
```json
"links": {
"self": "http:\/\/api.example.test\/api\/v1\/test-slug\/products\/1"
}
```

Add support for model bindings in route params

---

stubs/abstract/adapter.stub

fixes these errors on a freshly generated abstract adapter:
```
Declaration of App\JsonApi\Adapters\SearchResultAdapter::exists($resourceId) must be compatible with CloudCreativity\LaravelJsonApi\Contracts\Adapter\ResourceAdapterInterface::exists(string $resourceId): bool
```
```
Declaration of App\JsonApi\Adapters\SearchResultAdapter::findMany(array $resourceIds) must be compatible with CloudCreativity\LaravelJsonApi\Contracts\Adapter\ResourceAdapterInterface::findMany(iterable $resourceIds): iterable
```

Update abstract adapter stub

---

.travis.yml
composer.json

This pull request adds support for php 8. The Travis dist had to change to xenial, as it is the only dist on Travis that currently supports php 7.3 - 8.0.

Add support for php 8

---

.github/workflows/tests.yml
CHANGELOG.md
composer.json

Changes required to upgrade to Laravel 11. As Laravel 11 drops PHP 8.1, we'll do the same.

Feature: upgrade to Laravel 11 and drop PHP 8.1
